In [17]:
import pandas as pd

In [18]:
df_customer = pd.read_csv('customers.csv', sep=";")
df_customer

                                     UUID              Name  Points
0    aa3eaf74-6d9c-4859-b733-5a18a3b2f71b         afonso_rf     792
1    2d3d2dce-d353-4961-ad39-46723efe2100     mariicmartins    1375
2    ca95ef2a-5129-40f4-acbc-2ced25940032           tdlupus     421
3    65662aff-44d6-4f06-b9d9-07445c6e5943            kozat0    4063
4    98b960e7-6b7b-45b7-b7af-60bca40e04b9            gu1z17       0
..                                    ...               ...     ...
786  4a36c617-b018-436a-babc-4374461ab87b         null__var      53
787  403db18e-941e-4e63-ba23-e63c0515876a         lmadriles      50
788  c9bfbbf9-db90-45a7-a72c-4118140038f4  eduardo_cofferri      50
789  4caa2fb3-7ed2-436d-bc35-390feebfdebe          marmschu      50
790  000ff655-fa9f-4baa-a108-47f581ec52a1            cajuuh      52

[791 rows x 3 columns]

In [19]:
df_transactions = pd.read_excel('transactions.xlsx')
df_transactions

,UUID,IdCustomer,DtTransaction,Points
0,fb4e3102-6125-414e-b086-e7f641e38f93,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-01-27 11:53:23.774,1
1,036b8d66-8adf-479b-ba0f-cb0e3207acb0,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-01-27 11:53:24.643,1
2,10166182-a164-4608-8cdf-35e4450b2bd7,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-01-27 12:11:44.728,500
3,03974c58-e86e-4b6b-8143-8f89ca870d09,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-01-27 12:19:41.063,1
4,e84703a6-b606-4096-a2f3-514971c16c5c,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-01-27 12:31:46.288,500
...,...,...,...,...
23497,25500149-c2b8-4942-90f7-39f136d9fb1b,2d7f6b3f-9366-44c1-9663-beb5f7e1254e,2024-03-04 12:24:18.083,1
23498,75b3856f-083d-4775-98c9-7a9791b4d693,0ed6b09e-4329-4d2a-837b-2aad4796cd3a,2024-03-04 12:24:27.976,1
23499,827a1417-902c-4657-a0e5-4cef5d2bd8ca,0ed6b09e-4329-4d2a-837b-2aad4796cd3a,2024-03-04 12:25:13.024,1
23500,7429b0a5-08a5-470c-8091-12f627d21911,f3a268f2-1788-47da-bc79-2680a1721254,2024-03-04 12:25:28.565,50
23501,07d25502-18a9-4107-b4af-9b5ba8b5a46d,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-03-04 12:26:03.369,1

In [20]:
df_transactions_product = pd.read_parquet('transactions_cart.parquet')
df_transactions_product

,UUID,IdTransaction,Product,Quantity
0,52a8d2f8-c9d2-4dcc-b8ab-48992a3dbe8f,fb4e3102-6125-414e-b086-e7f641e38f93,ChatMessage,1
1,7c5bf868-38be-4532-a7b9-2283a4e414a4,036b8d66-8adf-479b-ba0f-cb0e3207acb0,ChatMessage,1
2,16994050-9ad6-4c03-b245-eb47680d3754,10166182-a164-4608-8cdf-35e4450b2bd7,Resgatar Ponei,1
3,56752b13-fb35-4c30-8f4b-033c606f718c,03974c58-e86e-4b6b-8143-8f89ca870d09,ChatMessage,1
4,164f6cd5-c510-45f9-882d-fd9f7d0de704,e84703a6-b606-4096-a2f3-514971c16c5c,Resgatar Ponei,1
...,...,...,...,...
23497,f6b3fdc1-3489-4757-874b-2ba3bdbfbbf1,25500149-c2b8-4942-90f7-39f136d9fb1b,ChatMessage,1
23498,8154636b-5fc9-4ec0-9564-ff9573f9a2b3,75b3856f-083d-4775-98c9-7a9791b4d693,ChatMessage,1
23499,114f515e-b29a-4714-a6ad-2a5437c72e75,827a1417-902c-4657-a0e5-4cef5d2bd8ca,ChatMessage,1
23500,83cf5662-2f1c-4112-a36e-404e28e241eb,7429b0a5-08a5-470c-8091-12f627d21911,Lista de presença,1
23501,8a11910b-1b57-484d-b618-7f1e20f2c93c,07d25502-18a9-4107-b4af-9b5ba8b5a46d,ChatMessage,1

In [21]:
df_join = (df_transactions.merge(df_customer,
                                how="inner",
                                left_on="IdCustomer",
                                right_on="UUID",
                                suffixes=["_transacao", "_cliente"])
                          .merge(df_transactions_product,
                                 how='inner',
                                 left_on="UUID_transacao",
                                 right_on="IdTransaction")
                                 )

df_join

,UUID_transacao,IdCustomer,DtTransaction,Points_transacao,UUID_cliente,Name,Points_cliente,UUID,IdTransaction,Product,Quantity
0,ac18e5fd-eb6e-4d83-9bf1-bd8973fcd1b4,2d3d2dce-d353-4961-ad39-46723efe2100,2024-01-29 11:55:05.127,1,2d3d2dce-d353-4961-ad39-46723efe2100,mariicmartins,1375,5b812be4-8f4f-4fb7-ab2b-f181f7fb37f9,ac18e5fd-eb6e-4d83-9bf1-bd8973fcd1b4,ChatMessage,1
1,f5f48f35-94bd-4df8-ac57-7566ce2f09a1,2d3d2dce-d353-4961-ad39-46723efe2100,2024-01-29 11:56:56.113,1,2d3d2dce-d353-4961-ad39-46723efe2100,mariicmartins,1375,237fe162-cd6d-42e0-8491-b47f513f7c64,f5f48f35-94bd-4df8-ac57-7566ce2f09a1,ChatMessage,1
2,270948e3-a015-4255-be6a-36010d26b74d,c4f241f8-2140-4f72-b1a3-904fcc51e38c,2024-01-29 11:57:14.602,1,c4f241f8-2140-4f72-b1a3-904fcc51e38c,otal_xandao,203,0c9bb1a1-a9ec-4040-9470-dea7421f345e,270948e3-a015-4255-be6a-36010d26b74d,ChatMessage,1
3,78ba1dcf-9bed-4e0d-abd3-58ff60d4b47d,2d3d2dce-d353-4961-ad39-46723efe2100,2024-01-29 11:58:21.812,1,2d3d2dce-d353-4961-ad39-46723efe2100,mariicmartins,1375,fc918e6d-716f-4877-9059-107d801b004b,78ba1dcf-9bed-4e0d-abd3-58ff60d4b47d,ChatMessage,1
4,6a736d67-ed53-446a-b558-d9e6b671f0b9,2d3d2dce-d353-4961-ad39-46723efe2100,2024-01-29 11:58:23.748,1,2d3d2dce-d353-4961-ad39-46723efe2100,mariicmartins,1375,4b98387c-0e66-4442-bbcc-094eed640344,6a736d67-ed53-446a-b558-d9e6b671f0b9,ChatMessage,1
...,...,...,...,...,...,...,...,...,...,...,...
18853,aeb17cd4-36ae-43ae-9c18-c37fb91f292e,3f55b86f-dc21-4ac8-8e89-7c1535359eaf,2024-03-04 12:24:09.030,1,3f55b86f-dc21-4ac8-8e89-7c1535359eaf,tapioca_amin,1394,41911803-b85e-434d-85f6-c2eebff03bc8,aeb17cd4-36ae-43ae-9c18-c37fb91f292e,ChatMessage,1
18854,25500149-c2b8-4942-90f7-39f136d9fb1b,2d7f6b3f-9366-44c1-9663-beb5f7e1254e,2024-03-04 12:24:18.083,1,2d7f6b3f-9366-44c1-9663-beb5f7e1254e,pipinstallsocialism,26,f6b3fdc1-3489-4757-874b-2ba3bdbfbbf1,25500149-c2b8-4942-90f7-39f136d9fb1b,ChatMessage,1
18855,75b3856f-083d-4775-98c9-7a9791b4d693,0ed6b09e-4329-4d2a-837b-2aad4796cd3a,2024-03-04 12:24:27.976,1,0ed6b09e-4329-4d2a-837b-2aad4796cd3a,x_deathking_x,55,8154636b-5fc9-4ec0-9564-ff9573f9a2b3,75b3856f-083d-4775-98c9-7a9791b4d693,ChatMessage,1
18856,827a1417-902c-4657-a0e5-4cef5d2bd8ca,0ed6b09e-4329-4d2a-837b-2aad4796cd3a,2024-03-04 12:25:13.024,1,0ed6b09e-4329-4d2a-837b-2aad4796cd3a,x_deathking_x,55,114f515e-b29a-4714-a6ad-2a5437c72e75,827a1417-902c-4657-a0e5-4cef5d2bd8ca,ChatMessage,1
18857,7429b0a5-08a5-470c-8091-12f627d21911,f3a268f2-1788-47da-bc79-2680a1721254,2024-03-04 12:25:28.565,50,f3a268f2-1788-47da-bc79-2680a1721254,nabuchadresar,205,83cf5662-2f1c-4112-a36e-404e28e241eb,7429b0a5-08a5-470c-8091-12f627d21911,Lista de presença,1